const campeonesF1 = [
  { temporada: 2023, piloto: "Max Verstappen", escuderia: "Red Bull Racing" },
  { temporada: 2022, piloto: "Max Verstappen", escuderia: "Red Bull Racing" },
  { temporada: 2021, piloto: "Max Verstappen", escuderia: "Red Bull Racing" },
  { temporada: 2020, piloto: "Lewis Hamilton", escuderia: "Mercedes-AMG Petronas Formula One Team" },
  { temporada: 2019, piloto: "Lewis Hamilton", escuderia: "Mercedes-AMG Petronas Formula One Team" },
  { temporada: 2018, piloto: "Lewis Hamilton", escuderia: "Mercedes-AMG Petronas Formula One Team" },
  { temporada: 2017, piloto: "Lewis Hamilton", escuderia: "Mercedes-AMG Petronas Formula One Team" },
  { temporada: 2016, piloto: "Nico Rosberg", escuderia: "Mercedes-AMG Petronas Formula One Team" },
  { temporada: 2015, piloto: "Lewis Hamilton", escuderia: "Mercedes-AMG Petronas Formula One Team" },
  { temporada: 2014, piloto: "Lewis Hamilton", escuderia: "Mercedes-AMG Petronas Formula One Team" },
  { temporada: 2013, piloto: "Sebastian Vettel", escuderia: "Red Bull Racing" },
  { temporada: 2012, piloto: "Sebastian Vettel", escuderia: "Red Bull Racing" },
  { temporada: 2011, piloto: "Sebastian Vettel", escuderia: "Red Bull Racing" },
  { temporada: 2010, piloto: "Sebastian Vettel", escuderia: "Red Bull Racing" },
  { temporada: 2009, piloto: "Jenson Button", escuderia: "Brawn GP" },
  { temporada: 2008, piloto: "Lewis Hamilton", escuderia: "Mercedes-AMG Petronas Formula One Team" },
  { temporada: 2007, piloto: "Kimi Räikkönen", escuderia: "Scuderia Ferrari" },
  { temporada: 2006, piloto: "Fernando Alonso", escuderia: "Renault" },
  { temporada: 2005, piloto: "Fernando Alonso", escuderia: "Renault" },
  { temporada: 2004, piloto: "Michael Schumacher", escuderia: "Scuderia Ferrari" },
  { temporada: 2003, piloto: "Michael Schumacher", escuderia: "Scuderia Ferrari" },
  { temporada: 2002, piloto: "Michael Schumacher", escuderia: "Scuderia Ferrari" },
  { temporada: 2001, piloto: "Michael Schumacher", escuderia: "Scuderia Ferrari" },
  { temporada: 2000, piloto: "Michael Schumacher", escuderia: "Scuderia Ferrari" },
  { temporada: 1999, piloto: "Mika Häkkinen", escuderia: "McLaren" },
  { temporada: 1998, piloto: "Mika Häkkinen", escuderia: "McLaren" },
  { temporada: 1997, piloto: "Jacques Villeneuve", escuderia: "Williams" },
  { temporada: 1996, piloto: "Damon Hill", escuderia: "Williams" },
  { temporada: 1995, piloto: "Michael Schumacher", escuderia: "Benetton Formula" },
  { temporada: 1994, piloto: "Michael Schumacher", escuderia: "Benetton Formula" },
  { temporada: 1993, piloto: "Alain Prost", escuderia: "Williams" },
  { temporada: 1992, piloto: "Nigel Mansell", escuderia: "Williams" },
  { temporada: 1991, piloto: "Ayrton Senna", escuderia: "McLaren" },
  { temporada: 1990, piloto: "Ayrton Senna", escuderia: "McLaren" },
  { temporada: 1989, piloto: "Alain Prost", escuderia: "McLaren" },
  { temporada: 1988, piloto: "Ayrton Senna", escuderia: "McLaren" },
  { temporada: 1987, piloto: "Nelson Piquet", escuderia: "Williams" },
  { temporada: 1986, piloto: "Alain Prost", escuderia: "McLaren" },
  { temporada: 1985, piloto: "Alain Prost", escuderia: "McLaren" },
  { temporada: 1984, piloto: "Niki Lauda", escuderia: "McLaren" },
  { temporada: 1983, piloto: "Nelson Piquet", escuderia: null },
  { temporada: 1981, piloto: "Nelson Piquet", escuderia: null },
  { temporada: 1977, piloto: "Niki Lauda", escuderia: "Scuderia Ferrari" },
  { temporada: 1976, piloto: "James Hunt", escuderia: "McLaren" },
  { temporada: 1975, piloto: "Niki Lauda", escuderia: "Scuderia Ferrari" }
];
